### ISSUE TITLE
Option 1 - Install on your machine

### ISSUE THREAD

**Issue by anilbb23a** [jbossdemocentral/bpms-install-demo#16]
While executing init.bat with jboss-bpmsuite-installer-6.2.0.BZ-1299002.jar.
I am getting error while installing bpmsuite..

Applying JBoss EAP patch now...
{
    "outcome" : "success",
    "result" : {}
}

BPM Suite installer running now...

[ Starting automated installation ]
No 'jar' binary detected in PATH. Please make sure this binary exists before continuing the installation.
[ Automated installation FAILED! ]

Error Occurred During JBoss BPM Suite Installation!

**Comment by sbjorng** [comment]
Apparently it is related to using a JRE instead of the full SDK, solved this issue by installing SDK and pointing JAVA_HOME to it

**Comment by DuncanDoyle** [comment]
I've released a new version of the demo today, which includes a new Powershell-based install script (and an upgrade to EAP 7 and BPM Suite 6.4.0). Closing this issue.
