### ISSUE TITLE
Support for EAP 7.0 and BPMNS 6.3.0.GA

### ISSUE THREAD

**Issue by eximius313** [jbossdemocentral/bpms-install-demo#17]
`EAP 7.0` and `BPMNS 6.3.0.GA` are the current versions.

Could you please provide support for them?

**Comment by DuncanDoyle** [comment]
BPMSuite 6.3.0.GA is not verified, tested and/or supported on EAP 7, hence, I'll not support that combination until BPMSuite is officially supported on that platform.

I want to upgrade to BPMSuite 6.3.0.GA however, but that does require an EAP 6.x patch to be available, which is currently only available to Red Hat customers. Given that this is a public demo, I don't want it to depend on files that are not publicly available (currently chasing a solution to this problem).

**Comment by DuncanDoyle** [comment]
BPM Suite 6.4.0.GA will provide support for EAP 7. I will upgrade the demo's to those versions when 6.4.0.GA has been released.

**Comment by DuncanDoyle** [comment]
Fixed by https://github.com/jbossdemocentral/bpms-install-demo/commit/0c95a8a82c0a5cbf86116eecd30ab5ede265b07e
