### ISSUE TITLE
init.bat fill removed?

### ISSUE THREAD

**Issue by chengkuangan** [jbossdemocentral/bpms-install-demo#21]
Seems like most of the demo is without init.bat, not supporting windows anymore? I use the demo central a lot to enable my partner and ISVs, most of the developers here are still using windows OS

**Comment by eschabell** [comment]
@chengkuangan, 

Looks like @DuncanDoyle's last commit was to remove the init.bat in favor of power shell scripts, but they never got added https://github.com/jbossdemocentral/bpms-install-demo/commit/4ae719acb3abaa6dacd486d09856424f6faa773b.

On another note, would you mind trying out the init.bat version found here for BRMS on OpenShift Container Platform (running in a container)? 

Comments from a windows tester would be welcome: https://github.com/redhatdemocentral/rhcs-brms-install-demo

**Comment by chengkuangan** [comment]
Hi Erics,

Will try this, thanks


Thank you.

Kind Regards,

Gan Cheng Kuan
Senior Solution Architect for ASEAN (ISV & Partners)
Red Hat Malaysia Sdn Bhd
Mobile: (60) 012-6581713
Email: chgan@redhat.com

On 11 Jul 2017, at 4:07 PM, Eric D. Schabell <notifications@github.com>
wrote:

@chengkuangan <https://github.com/chengkuangan>,

Looks like @DuncanDoyle <https://github.com/duncandoyle>'s last commit was
to remove the init.bat in favor of power shell scripts, but they never got
added 4ae719a
<https://github.com/jbossdemocentral/bpms-install-demo/commit/4ae719acb3abaa6dacd486d09856424f6faa773b>
.

On another note, would you mind trying out the init.bat version found here
for BRMS on OpenShift Container Platform (running in a container)?

Comments from a windows tester would be welcome:
https://github.com/redhatdemocentral/rhcs-brms-install-demo

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jbossdemocentral/bpms-install-demo/issues/21#issuecomment-314367428>,
or mute the thread

**Comment by DuncanDoyle** [comment]
init.ps1 file is there: https://github.com/jbossdemocentral/bpms-install-demo/blob/master/init.ps1

Has been there since this commit on November 18 2016: https://github.com/jbossdemocentral/bpms-install-demo/commit/0e996c5f6cbf0f63012f732c37ce040eda6a4267#diff-4109fc523b0fe2ff4ab4d6d6e8040146

Documentation was also updated to point to this file: https://github.com/jbossdemocentral/bpms-install-demo/#option-1---install-on-your-machine

**Comment by DuncanDoyle** [comment]
Note that we now also provide a PowerShell script to build the Docker container as well: 'https://github.com/jbossdemocentral/bpms-install-demo/blob/master/init-docker.ps1'. So that should provide you a 1-click install on Windows, given that you've got Docker installed on your Windows machine.
