### ISSUE TITLE
BPM suite install fails on Windows 10

### ISSUE THREAD

**Issue by MartinReinke** [jbossdemocentral/bpms-install-demo#23]
I tried to get jboss BPM on my windows 10 machine to set it up, but struggled and some how did not succeed in the end.

First I needed to do fixing the bug with allowing local powershell execution, to circumvent this error:

PS C:\Program Files (x86)\jbossBPM\bpms-install-demo-master> .\init.ps1
.\init.ps1 : File C:\Program Files (x86)\jbossBPM\bpms-install-demo-master\init.ps1 cannot be loaded because running
scripts is disabled on this system. For more information, see about_Execution_Policies at
http://go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ .\init.ps1
+ ~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

​Do this ​with this command
PS C:\Program Files (x86)\jbossBPM\bpms-install-demo-master> Get-ExecutionPolicy
Restricted
PS C:\Program Files (x86)\jbossBPM\bpms-install-demo-master> Set-ExecutionPolicy -ExecutionPolicy RemoteSigned

Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose
you to the security risks described in the about_Execution_Policies help topic at
http://go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y
PS C:\Program Files (x86)\jbossBPM\bpms-install-demo-master>

​Then I had to correct the downloaded files and directory copies according to your script to have,
it was rather more a layer 8 problem on my side but easy to fix

PS C:\Program Files (x86)\jbossBPM\bpms-install-demo-master\installs> ls
    Directory: C:\Program Files (x86)\jbossBPM\bpms-install-demo-master\installs
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       26.10.2017     19:24      238927691 jboss-bpmsuite-6.4.0.GA-deployable-eap7.x.zip
-a----       26.10.2017     18:42      306206910 jboss-bpmsuite-6.4.0.GA-installer.jar
-a----       26.10.2017     18:48      184545112 jboss-eap-7.0.0-installer.jar
------       29.11.2016     10:01            369 README

I had to download and install Oracle Java JDK 1.9 and add JDK and JRE to PATH
as well as to download and install 7-zip, reboot Windows 10 and add 7-zip to PATH​

After all that has been done the init.ps script is running, without complaining for pre-reqs to be done.
But then failing with this error

![grafik](https://user-images.githubusercontent.com/8319661/32096276-4050f0ba-bb06-11e7-9cf7-4baa60e9fe33.png)

Do you have an idea what might be missing or wrong???

**Comment by DuncanDoyle** [comment]
My first guess would be path length .... Windows (even in 2017) only accepts 256 characters in a path, and when you unzip something like JBoss EAP, especially the "modules" directory in EAP, you can easily exceed that path-length limit if you already start with a very long base-path.

I really don't understand why modern Windows systems still have this limitation to be honest, this was already hurting me back in 2004 ....

Can you try reducing the length of the path from which you start installing this demo?

**Comment by MartinReinke** [comment]
Hey Duncan,

Seems to be something else... no success yet.
Are you maybe available next week Tuesday  or Wednesday for BJNs?

I hate not getting it up and running

Mit freundlichen Grüßen / Kind regards
Martin Reinke

Senior Solution Architekt | Red Hat Germany
📞 +49 175 9195817   📧 mreinke@redhat.com
von meinem iPhone gesendet

Am 27.10.2017 um 11:57 schrieb Duncan Doyle <notifications@github.com>:

My first guess would be path length .... Windows (even in 2017) only
accepts 256 characters in a path, and when you unzip something like JBoss
EAP, especially the "modules" directory in EAP, you can easily exceed that
path-length limit if you already start with a very long base-path.

I really don't understand why modern Windows systems still have this
limitation to be honest, this was already hurting me back in 2004 ....

Can you try reducing the length of the path from which you start installing
this demo?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jbossdemocentral/bpms-install-demo/issues/23#issuecomment-339928676>,
or mute the thread

**Comment by MartinReinke** [comment]
I switched working directory up to c:\jbossBPM, but it seems to not has any impact.
same error message. 
What error is potentially localized in line 1 char 1 within the file init1.ps1

**Comment by DuncanDoyle** [comment]
I have tried again to reproduce this, and I really can't (tested again on Windows 10). I'm going to close this issue. Please re-open if this still is a problem.
